#!/bin/bash
#

R_PROFILE_USER=""
R_LIBS="" 

#Setting variables:
#
#DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
#source ${DIR}/../configfile

RSCRIPT=/packages/7x/r/4.0.2/bin/Rscript #add your own path to Rscript here

wf=all

if [ "$wf" == "all" ] ; then
	${RSCRIPT} --vanilla --default-packages=methods,datasets,utils,grDevices,graphics,stats  STRIPEseq_wf1.Rscript > STRIPEseq_Ptwf1.output
	${RSCRIPT} --default-packages=methods,datasets,utils,grDevices,graphics,stats  STRIPEseq_wf2.Rscript > STRIPEseq_Ptwf2.output
	${RSCRIPT} --default-packages=methods,datasets,utils,grDevices,graphics,stats  STRIPEseq_wf3.Rscript > STRIPEseq_Ptwf3.output
	${RSCRIPT} --default-packages=methods,datasets,utils,grDevices,graphics,stats  STRIPE_seqwf4.Rscript > STRIPEseq_Ptwf4.output
else
        ${RSCRIPT} --default-packages=methods,datasets,utils,grDevices,graphics,stats  ${EXPERIMENT}wf${wf}.Rscript > ${EXPERIMENT}wf${wf}.output
fi
